services:
  - type: web
    name: syllabus-calendar-converter
    env: python
    runtime: python-3.11.6
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 1 --timeout 300 --worker-class sync --max-requests 1000 --max-requests-jitter 50 -b 0.0.0.0:$PORT app:app"
    healthCheckPath: /
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: GEMINI_API_KEY
        sync: false
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.11.6
    disk:
      name: uploads
      mountPath: /opt/render/project/src/uploads
      sizeGB: 1
